In [3]:
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage, BaseMessage

model = ChatOpenAI(model="gpt-4o-mini", temperature=0)

messages = [
    SystemMessage(content="You are a helpful assistant."),
    HumanMessage(content="What is the capital of France?"),
]

response = model.invoke(messages, n=2)
print(response)


content='The capital of France is Paris.' additional_kwargs={'refusal': None} response_metadata={'finish_reason': 'stop', 'logprobs': None} id='run-f01c0b2d-0b50-4619-9e6c-ebd32fe00124-0' usage_metadata={'input_tokens': 24, 'output_tokens': 14, 'total_tokens': 38, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 0}}


In [8]:
model.generate([[HumanMessage(content="What is the capital of France?")]], n=2)


LLMResult(generations=[[ChatGeneration(text='The capital of France is Paris.', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='The capital of France is Paris.', additional_kwargs={'refusal': None}, response_metadata={'finish_reason': 'stop', 'logprobs': None}, id='run-9541ad8f-4cef-4dc6-96c5-e374dd4e4664-0', usage_metadata={'input_tokens': 14, 'output_tokens': 14, 'total_tokens': 28, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 0}})), ChatGeneration(text='The capital of France is Paris.', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='The capital of France is Paris.', additional_kwargs={}, response_metadata={'finish_reason': 'stop', 'logprobs': None}, id='run-9541ad8f-4cef-4dc6-96c5-e374dd4e4664-1', usage_metadata={'input_tokens': 14, 'output_tokens': 14, 'total_tokens': 28, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 0}}))]], llm_outpu

In [16]:
import numpy as np

def transform(grid: np.ndarray) -> np.ndarray:
    # Get the dimensions of the input grid
    rows, cols = grid.shape
    
    # Create an output grid of size 6x6
    output = np.empty((6, 6), dtype=object)
    
    for i in range(6):
        for j in range(6):
            # Fill the output grid with alternating colors based on the input grid
            output[i, j] = grid[i % rows, j % cols]
    
    return output

grid = np.array([[7, 9], [4, 3]])
output = transform(grid)
print(output.dtype)
print(output.ndim)
print(output)


object
2
[[7 9 7 9 7 9]
 [4 3 4 3 4 3]
 [7 9 7 9 7 9]
 [4 3 4 3 4 3]
 [7 9 7 9 7 9]
 [4 3 4 3 4 3]]
